apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dd-manager.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dd-manager.name" . }}
    helm.sh/chart: {{ include "dd-manager.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dd-manager.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "dd-manager.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}