apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "dd-manager.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dd-manager.name" . }}
    helm.sh/chart: {{ include "dd-manager.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  DD_API_KEY: {{ .Values.datadog.apiKey | b64enc }}
  DD_APP_KEY: {{ .Values.datadog.appKey | b64enc }}